"""new fields in user model

Revision ID: 229ec8d7dc74
Revises: 8b141614046e
Create Date: 2019-12-12 15:41:31.288846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '229ec8d7dc74'
down_revision = '8b141614046e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('color', sa.String(length=6), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'color')
    # ### end Alembic commands ###
